default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>

development:
  <<: *default
  database: trenja_dev

test:
  <<: *default
  database: trenja_test

production:
  <<: *default
  database: trenja_prod
